# Generated by Django 4.1.1 on 2022-10-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_courses_lesson_courseteachers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="create_date",
            new_name="created",
        ),
    ]
